import { join } from "node:path";
import babel from "@rolldown/plugin-babel";
import tailwindcss from "@tailwindcss/vite";
import react, { reactCompilerPreset } from "@vitejs/plugin-react";
import { defineConfig, lazyPlugins } from "vite-plus";
import { playwright } from "vite-plus/test/browser-playwright";

export default defineConfig({
  test: {
    // `.claude/worktrees/` holds checkouts of other branches; their tests are
    // not this one's to run.
    exclude: ["**/node_modules/**", "**/dist/**", ".claude/**"],
    projects: [
      {
        extends: true,
        test: {
          name: "node",
          // Every source file, `.tsx` included: a test written in a component's
          // own file would otherwise be collected by nothing and pass by never
          // having run.
          includeSource: ["src/**/*.{ts,tsx}"],
          exclude: ["**/node_modules/**", "**/dist/**", ".claude/**", "**/*.browser.test.tsx"],
        },
      },
      {
        extends: true,
        test: {
          name: "browser",
          include: ["src/**/*.browser.test.tsx"],
          setupFiles: ["src/test/setup.ts"],
          browser: {
            enabled: true,
            provider: playwright(),
            headless: true,
            // The window `tauri.conf.json` opens. The default viewport is a
            // phone's, which is not a shape this app is ever asked to be:
            // the grid's virtualized rows and the sidebar beside them both
            // depend on how much room there is.
            instances: [{ browser: "chromium", viewport: { width: 1280, height: 800 } }],
          },
        },
      },
    ],
    coverage: {
      // Every source file, not only the ones a test happened to import: a file
      // nothing covers is the point of measuring.
      include: ["src/**/*.{ts,tsx}"],
      exclude: ["src/bindings/**", "src/main.tsx", "src/**/*.test.*"],
      // The same table twice: on the terminal, and in a file for CI to put in
      // the run's summary.
      reporter: ["text", ["text", { file: "coverage.txt", maxCols: 160 }], "lcov"],
      // A file that is fully covered still belongs in the table: leaving it
      // out makes a reader wonder whether it was measured at all.
      skipFull: false,
    },
  },
  // Monaco is reached through 21 separate feature entry points, which Vite
  // otherwise discovers one crawl too late: it re-optimizes mid-run and reloads
  // the page under whichever test mounted the editor first.
  resolve: {
    alias: {
      // The package entry a browser is offered is a UMD bundle that calls
      // `require`, which nothing in a browser answers. This is the ESM build,
      // named by its path because an alias replaces a prefix and the package's
      // own name is the prefix. It imports the same Monaco module the editor
      // already holds, so there is one of it.
      "monaco-vim": join(import.meta.dirname, "node_modules/monaco-vim/dist/index.mjs"),
      // That build reaches into Monaco by a path its package does not publish
      // (`./*` maps to `./esm/vs/*.js`, so the prefix is applied twice). Taking
      // the prefix off lands on the same module the editor imports, which is
      // what keeps one Monaco in the page rather than two.
      "monaco-editor/esm/vs/": "monaco-editor/",
    },
  },

  optimizeDeps: {
    include: ["monaco-editor/**"],
    // monaco-vim's package entry for a browser is a UMD bundle that calls
    // `require`, which the optimizer cannot pre-bundle — it sits there instead
    // of failing. Left out of it, the ESM build is served as it is.
    exclude: ["monaco-vim"],
  },

  // Strips the in-source tests from production bundles.
  define: {
    "import.meta.vitest": "undefined",
  },

  // `src/bindings/` is generated by ts-rs (`cargo test`); leave it alone.
  fmt: {
    printWidth: 100,
    ignorePatterns: ["src/bindings/**"],
  },
  lint: {
    ignorePatterns: ["src/bindings/**"],
    plugins: ["react", "typescript", "unicorn", "oxc"],
    options: {
      typeAware: true,
      typeCheck: true,
    },
    jsPlugins: [{ name: "vite-plus", specifier: "vite-plus/oxlint-plugin" }],
    rules: {
      "vite-plus/prefer-vite-plus-imports": "error",
      "react/exhaustive-deps": "error",
      "react/rules-of-hooks": "error",
      "react/only-export-components": "warn",
      // The React Compiler memoizes for us; see CLAUDE.md.
      "no-restricted-imports": [
        "error",
        {
          paths: [
            {
              name: "react",
              importNames: ["memo", "useCallback", "useMemo"],
              message:
                "The React Compiler memoizes for you. Remove it, or disable this rule with a reason.",
            },
          ],
        },
      ],
    },
  },

  // `lazyPlugins` keeps `vp check` / `vp lint` from loading the plugins.
  plugins: lazyPlugins(() => [react(), babel({ presets: [reactCompilerPreset()] }), tailwindcss()]),

  // Keep Rust compile errors on screen instead of clearing them on every reload.
  clearScreen: false,
  server: {
    // Tauri loads `devUrl` from tauri.conf.json, so the port must not drift.
    port: 1420,
    strictPort: true,
    watch: {
      // Tauri watches the Rust sources itself and restarts the app.
      ignored: ["**/src-tauri/**"],
    },
  },
});
