import babel from "@rolldown/plugin-babel";
import tailwindcss from "@tailwindcss/vite";
import react, { reactCompilerPreset } from "@vitejs/plugin-react";
import { defineConfig, lazyPlugins } from "vite-plus";

export default defineConfig({
  test: {
    includeSource: ["src/**/*.ts"],
  },
  // Strips the in-source tests from production bundles.
  define: {
    "import.meta.vitest": "undefined",
  },

  // `src/bindings/` is generated by ts-rs (`cargo test`); leave it alone.
  fmt: {
    printWidth: 100,
    ignorePatterns: ["src/bindings/**"],
  },
  lint: {
    ignorePatterns: ["src/bindings/**"],
    plugins: ["react", "typescript", "unicorn", "oxc"],
    options: {
      typeAware: true,
      typeCheck: true,
    },
    jsPlugins: [{ name: "vite-plus", specifier: "vite-plus/oxlint-plugin" }],
    rules: {
      "vite-plus/prefer-vite-plus-imports": "error",
      "react/exhaustive-deps": "error",
      "react/rules-of-hooks": "error",
      "react/only-export-components": "warn",
      // The React Compiler memoizes for us; see CLAUDE.md.
      "no-restricted-imports": [
        "error",
        {
          paths: [
            {
              name: "react",
              importNames: ["memo", "useCallback", "useMemo"],
              message:
                "The React Compiler memoizes for you. Remove it, or disable this rule with a reason.",
            },
          ],
        },
      ],
    },
  },

  // `lazyPlugins` keeps `vp check` / `vp lint` from loading the plugins.
  plugins: lazyPlugins(() => [react(), babel({ presets: [reactCompilerPreset()] }), tailwindcss()]),

  // Keep Rust compile errors on screen instead of clearing them on every reload.
  clearScreen: false,
  server: {
    // Tauri loads `devUrl` from tauri.conf.json, so the port must not drift.
    port: 1420,
    strictPort: true,
    watch: {
      // Tauri watches the Rust sources itself and restarts the app.
      ignored: ["**/src-tauri/**"],
    },
  },
});
