import { join } from "node:path";
import babel from "@rolldown/plugin-babel";
import tailwindcss from "@tailwindcss/vite";
import react, { reactCompilerPreset } from "@vitejs/plugin-react";
import { defineConfig, lazyPlugins } from "vite-plus";
import { playwright } from "vite-plus/test/browser-playwright";

export default defineConfig({
  test: {
    // `.claude/worktrees/` holds checkouts of other branches; their tests are
    // not this one's to run.
    exclude: ["**/node_modules/**", "**/dist/**", ".claude/**"],
    projects: [
      {
        extends: true,
        test: {
          name: "node",
          // `.tsx` too, or a test in a component's file would silently never run.
          includeSource: ["src/**/*.{ts,tsx}"],
          exclude: ["**/node_modules/**", "**/dist/**", ".claude/**", "**/*.browser.test.tsx"],
        },
      },
      {
        extends: true,
        test: {
          name: "browser",
          include: ["src/**/*.browser.test.tsx"],
          setupFiles: ["src/test/setup.ts"],
          browser: {
            enabled: true,
            provider: playwright(),
            headless: true,
            // The window `tauri.conf.json` opens, rather than a phone's.
            instances: [{ browser: "chromium", viewport: { width: 1280, height: 800 } }],
          },
        },
      },
    ],
    coverage: {
      // Every source file: one no test imports is the point of measuring.
      include: ["src/**/*.{ts,tsx}"],
      exclude: ["src/bindings/**", "src/main.tsx", "src/**/*.test.*"],
      // `coverage.txt` is what CI puts on the run's summary page.
      reporter: ["text", ["text", { file: "coverage.txt", maxCols: 160 }], "lcov"],
      skipFull: false,
    },
  },
  resolve: {
    alias: {
      // The package's browser entry is a UMD bundle that calls `require`. An
      // absolute path, because an alias matches a prefix and would match itself.
      "monaco-vim": join(import.meta.dirname, "node_modules/monaco-vim/dist/index.mjs"),
      // monaco-vim imports a path Monaco's exports do not publish (`./*` already
      // maps to `./esm/vs/*.js`). This lands on the module the editor imports,
      // so there is one Monaco in the page rather than two.
      "monaco-editor/esm/vs/": "monaco-editor/",
    },
  },

  optimizeDeps: {
    // Imported lazily. Discovered mid-run, they are optimized mid-run and the
    // page reloads under a browser test.
    include: ["monaco-editor/**", "@tauri-apps/api/event"],
    // The optimizer hangs on its UMD entry rather than failing.
    exclude: ["monaco-vim"],
  },

  // Strips the in-source tests from production bundles.
  define: {
    "import.meta.vitest": "undefined",
  },

  // `src/bindings/` is generated by ts-rs (`cargo test`); leave it alone.
  fmt: {
    printWidth: 100,
    ignorePatterns: ["src/bindings/**"],
  },
  lint: {
    ignorePatterns: ["src/bindings/**"],
    plugins: ["react", "typescript", "unicorn", "oxc"],
    options: {
      typeAware: true,
      typeCheck: true,
    },
    jsPlugins: [{ name: "vite-plus", specifier: "vite-plus/oxlint-plugin" }],
    rules: {
      "vite-plus/prefer-vite-plus-imports": "error",
      "react/exhaustive-deps": "error",
      "react/rules-of-hooks": "error",
      "react/only-export-components": "warn",
      // The React Compiler memoizes for us; see CLAUDE.md.
      "no-restricted-imports": [
        "error",
        {
          paths: [
            {
              name: "react",
              importNames: ["memo", "useCallback", "useMemo"],
              message:
                "The React Compiler memoizes for you. Remove it, or disable this rule with a reason.",
            },
          ],
        },
      ],
    },
  },

  // `lazyPlugins` keeps `vp check` / `vp lint` from loading the plugins.
  plugins: lazyPlugins(() => [react(), babel({ presets: [reactCompilerPreset()] }), tailwindcss()]),

  // Keep Rust compile errors on screen instead of clearing them on every reload.
  clearScreen: false,
  server: {
    // Tauri loads `devUrl` from tauri.conf.json, so the port must not drift.
    port: 1420,
    strictPort: true,
    watch: {
      // Tauri watches the Rust sources itself and restarts the app.
      ignored: ["**/src-tauri/**"],
    },
  },
});
