// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AgentAccess = { enabled: boolean, 
/**
 * Empty until first opened. Shown to the reader to hand to an agent.
 */
token: string, 
/**
 * Chosen once and kept.
 */
port: number, };
