// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AgentAccess = { enabled: boolean, 
/**
 * What an agent has to present, and therefore a secret. It is shown to
 * the reader so that they can hand it to the agent they meant to.
 */
token: string, 
/**
 * Chosen once and kept: an agent configured with an address should not
 * have to be told a new one after every restart.
 */
port: number, };
