// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How the door stands, which is a row of meta.db and a secret of the
 * keychain's read together.
 */
export type AgentAccess = { enabled: boolean, 
/**
 * What an agent has to present. Empty until the door has been opened
 * once, and shown to the reader so they can hand it to the agent they
 * meant to.
 */
token: string, 
/**
 * Chosen once and kept.
 */
port: number, };
