// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Every command returns this on failure. It serializes as `{ kind, message }`
 * so the frontend can branch on `kind` instead of matching message text.
 * Unit variants serialize to `{ kind }` alone — no `message: null` to handle.
 */
export type AppError = { "kind": "NotFound", "message": string } | { "kind": "Validation", "message": string } | { "kind": "Internal", "message": string };
