// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `kind` lets the frontend branch on a failure without matching message text.
 */
export type AppError = { "kind": "Validation", "message": string } | { "kind": "NotFound", "message": string } | { "kind": "Database", "message": string } | { "kind": "Secret", "message": string };
