// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One command, as the frontend sees it: what it sends and what comes back.
 * The fields are never read — the type is here to be written out.
 */
export type Call<A, R> = { args: A, returns: R, };
