// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CandidateKind } from "./CandidateKind";

export type Candidate = { name: string, kind: CandidateKind, type_name: string | null, 
/**
 * What the name can be written after, where the column has one.
 */
qualifier: string | null, 
/**
 * How many queries out it comes from: 0 is the query the cursor is in.
 */
depth: number, };
