// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Shaped by the protocol, not by a type here.
 */
export type Capabilities = unknown;
