// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a server said it can do, in answer to `initialize`. The window reads
 * it as the protocol describes it, which is not a shape written down here.
 */
export type Capabilities = unknown;
