// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `cursor` is a UTF-16 offset into `text`, which is the whole of the
 * editor's document.
 */
export type CompleteArgs = { connection_id: string, text: string, cursor: number, };
