// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Candidate } from "./Candidate";
import type { TextSpan } from "./TextSpan";

/**
 * What could go where the cursor is. It says nothing about which driver it
 * came from, so that any of them can answer in it.
 */
export type Completion = { "kind": "names", replace: TextSpan, expected_type: string | null, candidates: Array<Candidate>, } | { "kind": "tables", replace: TextSpan, path: Array<string>, } | { "kind": "nothing" };
