// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DriverConfig } from "./DriverConfig";

export type ConnectionRecord = { id: string, label: string, config: DriverConfig, created_at: string, };
