// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DriverConfig } from "./DriverConfig";

export type ConnectionRecord = { id: string, label: string, config: DriverConfig, 
/**
 * A shell command the reader runs before connecting, if they gave one.
 */
command: string | null, 
/**
 * Whether the command runs only while this connection is selected.
 */
command_while_selected: boolean, 
/**
 * The IANA zone its points in time are shown in; UTC when absent.
 */
time_zone: string | null, 
/**
 * Marked as production: every statement that writes asks first.
 */
production: boolean, created_at: string, };
