// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A command that is about one connection and nothing more.
 */
export type ConnectionArgs = { connection_id: string, };
