// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DriverConfig } from "./DriverConfig";

export type ConnectionRecord = { id: string, label: string, config: DriverConfig, 
/**
 * A shell command the reader runs before connecting, if they gave one.
 */
command: string | null, created_at: string, };
