// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DriverConfig = { "kind": "postgres", host: string, port: number, database: string, username: string, } | { "kind": "bigquery", project_id: string, 
/**
 * Where the jobs run, and where the catalog that describes the
 * project lives: `US`, `EU`, `asia-northeast1`.
 */
location: string, };
