// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Unpruned } from "./Unpruned";

export type Estimate = { 
/**
 * An upper bound, and what on-demand pricing bills. Well within a JSON
 * number's exact range: that is eight pebibytes.
 */
bytes: number, unpruned: Array<Unpruned>, };
