// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Unpruned } from "./Unpruned";

export type Estimate = { 
/**
 * An upper bound, and what on-demand pricing bills. Well within a JSON
 * number's exact range: that is eight pebibytes.
 */
bytes: number, 
/**
 * The statement runs a string as SQL (`EXECUTE IMMEDIATE`), which the
 * dry run does not read, so `bytes` is only what the rest would scan.
 */
at_least: boolean, unpruned: Array<Unpruned>, };
