// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Handoff } from "./Handoff";
import type { LspExit } from "./LspExit";
import type { LspMessage } from "./LspMessage";
import type { ShellExit } from "./ShellExit";

/**
 * Every event the window may listen for, by name.
 */
export type Events = { "shell:exit": ShellExit, "lsp:message": LspMessage, "lsp:exit": LspExit, "agent:handoff": Handoff, };
