// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `query_id` is the caller's handle on the running statement, and what
 * `cancel_query` is handed to stop it.
 */
export type ExecuteQueryArgs = { connection_id: string, sql: string, query_id: string, };
