// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `analyze` carries the statement out to time it; it is cancelled like a
 * query, by `query_id`.
 */
export type ExplainQueryArgs = { connection_id: string, sql: string, analyze: boolean, query_id: string, };
