// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Handoff = { connection_id: string, sql: string, 
/**
 * What the agent called it; the window numbers it like any other tab
 * when there is none.
 */
title: string | null, };
