// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Hazard = "delete_without_where" | "update_without_where" | "drop" | "truncate" | "drop_column";
