// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Source } from "./Source";

export type HistoryEntry = { 
/**
 * ts-rs calls an `i64` a `bigint`, which is not what arrives: the row
 * crosses IPC as JSON, where serde writes the id as a number.
 */
id: number, sql: string, ran_at: string, duration_ms: number, row_count: number | null, error: string | null, source: Source, };
