// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An index of a table, as the tree lists it under the table.
 */
export type Index = { name: string, 
/**
 * `btree`, `gin`, …
 */
method: string, 
/**
 * The key columns or expressions, as `a, lower(b)`.
 */
keys: string, unique: boolean, primary: boolean, 
/**
 * On disk. Far below 2^53, so a JSON number holds it.
 */
bytes: number, };
