// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LanguageServerState = { "kind": "ready" } | { "kind": "missing", server: string, downloaded: boolean, } | { "kind": "named", message: string, };
