// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether a connection can be completed against, as far as the window needs
 * to know: one it could be, once there is a server to do it with, is the one
 * worth offering to build.
 */
export type LanguageServerState = { "kind": "ready" } | { "kind": "missing", server: string, } | { "kind": "named", message: string, };
