// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One JSON-RPC message, as the text the server is handed.
 */
export type LanguageServerMessageArgs = { connection_id: string, message: string, };
