// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A server that is no longer there. Whoever was talking to it should stop.
 */
export type LspExit = { connection_id: string, };
