// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Unparsed: what a message means is the window's business.
 */
export type LspMessage = { connection_id: string, payload: string, };
