// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a server said, as it said it. The window parses it: what a message
 * means is the client's business, and this is the pipe it arrives through.
 */
export type LspMessage = { connection_id: string, payload: string, };
