// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a page would be billed for.
 */
export type PreviewCost = { 
/**
 * Far below 2^53, so a JSON number holds it.
 */
bytes: number, };
