// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Sort } from "./Sort";

export type PreviewRequest = { connection_id: string, schema: string, table: string, 
/**
 * A WHERE expression the reader wrote, or empty for none.
 */
filter: string, sort: Sort | null, 
/**
 * Read each row's version too, which a caller asks for when it means to
 * offer editing.
 */
versioned: boolean, page: number, 
/**
 * Registers the preview where a running query would be, so `cancel_query`
 * stops either of them.
 */
query_id: string, };
