// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Sort } from "./Sort";

export type PreviewRequest = { connection_id: string, schema: string, table: string, 
/**
 * A WHERE expression the reader wrote, or empty for none.
 */
filter: string, sort: Sort | null, 
/**
 * Read each row's `xmin`, for editing.
 */
versioned: boolean, page: number, 
/**
 * An RFC 3339 point to read the table as it was then, or null for now.
 */
as_of: string | null, 
/**
 * So `cancel_query` stops a preview too.
 */
query_id: string, };
