// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What PostgreSQL's `EXPLAIN (FORMAT JSON)` said, left as it said it: a node
 * carries whichever of dozens of keys its type has, and all of them are shown.
 */
export type QueryPlan = { plan: unknown, elapsed_ms: number, };
