// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QueryColumn } from "./QueryColumn";

export type QueryResult = { columns: Array<QueryColumn>, 
/**
 * A cell is whatever JSON the driver made of the database value, so a
 * reader has to narrow it before rendering.
 */
rows: Array<Array<unknown>>, 
/**
 * The query had more rows than the limit the command asked for.
 */
truncated: boolean, elapsed_ms: number, };
