// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The statement is kept as written: finding its `@name` blanks and filling
 * them in is the window's, which knows how each driver quotes a value.
 */
export type QueryTemplate = { id: string, name: string, sql: string, };
