// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type QueryColumn = { name: string, type_name: string, 
/**
 * Its values, or its array's elements, are points in time, which cross in
 * UTC and may be shown in another zone. A type name cannot say so on its
 * own: BigQuery's `TIMESTAMP` is one, PostgreSQL's is not.
 */
instant: boolean, };
