// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Every connection, in the order the rail is to show them.
 */
export type ReorderConnectionsArgs = { connection_ids: Array<string>, };
