// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Hazard } from "./Hazard";

/**
 * A statement to ask about before it runs. A guard against slips, not a
 * permission: what the reader may do is still the role's to decide.
 */
export type Risk = { 
/**
 * The statement as the reader wrote it.
 */
statement: string, hazard: Hazard, 
/**
 * What it acts on, as written: `public.users`, or `users.email` for a
 * column. Empty when the statement names it in a way not worth repeating.
 */
targets: Array<string>, };
