// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RoutineKind } from "./RoutineKind";

/**
 * A function or procedure. Its definition is asked for when it is opened.
 */
export type Routine = { name: string, kind: RoutineKind, 
/**
 * What it takes, as `a integer, b text`. PostgreSQL tells overloads of one
 * name apart by it, so it is also what names the one to open.
 */
arguments: string, comment: string | null, };
