// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A function or procedure of a connection, as the tree names it.
 */
export type RoutineArgs = { connection_id: string, schema: string, name: string, arguments: string, };
