// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A row the reader removed, named and versioned as an update is.
 */
export type RowDelete = { key: { [key in string]: string | null }, version: string, };
