// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A row the reader added. A column left out of `values` takes whatever the
 * table gives it — a default, a sequence, or NULL.
 */
export type RowInsert = { values: { [key in string]: string | null }, };
