// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Values are the text the reader typed, or null for SQL NULL. `version` is
 * the `xmin` the row was read with, so a row changed since no longer matches.
 */
export type RowUpdate = { key: { [key in string]: string | null }, set: { [key in string]: string | null }, version: string, };
