// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One row the reader changed. Values travel as the text they typed, or null
 * for SQL NULL. `key` is the row's primary key, and `version` is the `xmin`
 * the row was read with: PostgreSQL writes the transaction that last touched
 * a row there, so a row someone else has changed no longer matches.
 */
export type RowUpdate = { key: { [key in string]: string | null }, set: { [key in string]: string | null }, version: string, };
