// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DriverConfig } from "./DriverConfig";

export type SaveConnectionInput = { 
/**
 * Absent for a new connection, present to update that one.
 */
id: string | null, label: string, config: DriverConfig, 
/**
 * Absent leaves the stored secret alone.
 */
secret: string | null, 
/**
 * A shell command to run before connecting, or nothing to run.
 */
command: string | null, };
