// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SavedTab } from "./SavedTab";

/**
 * A connection's tabs in the strip's order. `active` indexes `tabs`, and is
 * 0 when there are none.
 */
export type SavedTabs = { tabs: Array<SavedTab>, active: number, };
