// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A tab as it is reopened: what the reader wrote, or which table they were
 * reading. How a table was being read starts again from its first page.
 */
export type SavedTab = { "kind": "sql", title: string, sql: string, } | { "kind": "table", schema: string, table: string, };
