// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SavedTabs } from "./SavedTabs";

export type SaveTabsInput = { connection_id: string, tabs: SavedTabs, };
