// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SaveTemplateInput = { 
/**
 * Absent for a new template, present to update that one.
 */
id: string | null, name: string, sql: string, };
