// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Sequence = { name: string, 
/**
 * As text, since it may be past what a JavaScript number holds. `None`
 * before the first `nextval`, or when the role may not read it.
 */
last_value: string | null, 
/**
 * `table.column`, for a sequence a column's default or identity draws on.
 */
owned_by: string | null, comment: string | null, };
