// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ShellExit = { connection_id: string, 
/**
 * `None` when a signal ended it, which is what stopping one looks like.
 */
code: number | null, 
/**
 * True when this run was stopped on purpose. A command that dies on its
 * own is worth telling the reader about; one they stopped is not.
 */
stopped: boolean, 
/**
 * The last lines it wrote, stdout and stderr together in arrival order.
 */
output: string, };
