// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a table preview is ordered. `column` is an identifier the caller took
 * from the table's own columns.
 */
export type Sort = { column: string, descending: boolean, };
