// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An agent's statement still ran against the reader's database. A handoff did
 * not run: an agent gave it to the reader, whose run of it is their own.
 */
export type Source = "reader" | "agent" | "handoff";
