// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Who ran it. A statement an agent was asked for is still a statement that
 * ran against the reader's database, and which of them it was is what makes
 * the log worth keeping.
 */
export type Source = "reader" | "agent";
