// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An agent's statement still ran against the reader's database.
 */
export type Source = "reader" | "agent";
