// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Lines and columns count from 1, and columns in UTF-16 units, as the editor
 * does.
 */
export type SyntaxError = { message: string, start_line: number, start_column: number, end_line: number, end_column: number, };
