// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a statement went wrong, in the coordinates an editor marks in: lines
 * and columns count from 1, and a column counts UTF-16 units, because that is
 * what the editor measures a line in.
 */
export type SyntaxError = { 
/**
 * PostgreSQL's own complaint, unchanged.
 */
message: string, start_line: number, start_column: number, end_line: number, end_column: number, };
