// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Column } from "./Column";
import type { TableKind } from "./TableKind";

export type Table = { name: string, kind: TableKind, columns: Array<Column>, };
