// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a table's columns are called, what type each one has as PostgreSQL
 * prints it, and which of them the primary key is made of. A table with no
 * primary key cannot name a row, so it cannot be edited.
 */
export type TableShape = { types: { [key in string]: string }, primary_key: Array<string>, };
