// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A table with no primary key cannot name a row, so it cannot be edited.
 */
export type TableShape = { types: { [key in string]: string }, primary_key: Array<string>, };
