// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QueryResult } from "./QueryResult";

/**
 * Versions sit beside the rows rather than in a column the reader would see.
 */
export type TablePage = { result: QueryResult, versions: Array<string>, };
