// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NamedDefinition } from "./NamedDefinition";

/**
 * The `CREATE` statement, and the indexes and triggers it does not include.
 */
export type TableDefinition = { definition: string, indexes: Array<NamedDefinition>, triggers: Array<NamedDefinition>, };
