// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A command that is about one table of a connection.
 */
export type TableArgs = { connection_id: string, schema: string, table: string, };
