// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NamedDefinition } from "./NamedDefinition";

/**
 * What a table is, as PostgreSQL's own catalogs describe it: the `CREATE`
 * statement rebuilt from them, and the indexes and triggers that are not part
 * of it.
 */
export type TableDefinition = { definition: string, indexes: Array<NamedDefinition>, triggers: Array<NamedDefinition>, };
