// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TableKind } from "./TableKind";

/**
 * No columns: a project can hold tens of thousands of tables, so a table's
 * columns are asked for when it is opened.
 */
export type Table = { name: string, kind: TableKind, };
