// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RowDelete } from "./RowDelete";
import type { RowInsert } from "./RowInsert";
import type { RowUpdate } from "./RowUpdate";

export type TableEdits = { connection_id: string, schema: string, table: string, inserts: Array<RowInsert>, updates: Array<RowUpdate>, deletes: Array<RowDelete>, };
