// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TableKind } from "./TableKind";

/**
 * What a table holds is not here: a project can hold tens of thousands of
 * tables and many times that many columns, so the tree says what there is and
 * a table's columns are asked for when it is opened.
 */
export type Table = { name: string, kind: TableKind, };
