// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QueryResult } from "./QueryResult";

/**
 * A page of a table, with the version of each row beside the rows themselves
 * rather than in a column the reader would have to look at.
 */
export type TablePage = { result: QueryResult, versions: Array<string>, };
