// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A span of the text, in the UTF-16 units the editor counts in.
 */
export type TextSpan = { start: number, end: number, };
