// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where the reader's session stands between statements. BigQuery keeps no
 * session, so it is always `Idle` there.
 */
export type TransactionState = "idle" | "open" | "failed";
