// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `data_type` is `None` for an enum's label.
 */
export type TypeMember = { name: string, data_type: string | null, };
