// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A partitioned table the statement reads with no filter that could prune it.
 */
export type Unpruned = { 
/**
 * `project.dataset.table`.
 */
table: string, 
/**
 * What a filter would have to name.
 */
column: string, };
