// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TypeMember } from "./TypeMember";
import type { UserTypeKind } from "./UserTypeKind";

export type UserType = { name: string, kind: UserTypeKind, 
/**
 * What a domain narrows, or what a range ranges over.
 */
base: string | null, 
/**
 * An enum's labels, in their order, or a composite type's attributes.
 */
members: Array<TypeMember>, comment: string | null, };
